// 每日一句：关于时间、生命与珍惜当下的句子（本地预置，离线可用）
// B4：按语言分池，各语言用当地文化名言；按「一年中的第几天」取模轮换
// 缺池时回退 zh-CN，保证任何语言都有内容

export const QUOTES = {
  'zh-CN': [
  { text: '盛年不重来，一日难再晨。及时当勉励，岁月不待人。', author: '陶渊明' },
  { text: '悟已往之不谏，知来者之可追。', author: '陶渊明' },
  { text: '纵浪大化中，不喜亦不惧。应尽便须尽，无复独多虑。', author: '陶渊明' },
  { text: '死去何所道，托体同山阿。', author: '陶渊明' },
  { text: '人生无根蒂，飘如陌上尘。', author: '陶渊明' },
  { text: '逝者如斯夫，不舍昼夜。', author: '《论语》' },
  { text: '少壮不努力，老大徒伤悲。', author: '汉乐府《长歌行》' },
  { text: '生年不满百，常怀千岁忧。昼短苦夜长，何不秉烛游！', author: '《古诗十九首》' },
  { text: '对酒当歌，人生几何！譬如朝露，去日苦多。', author: '曹操' },
  { text: '岁月不居，时节如流。', author: '孔融' },
  { text: '年年岁岁花相似，岁岁年年人不同。', author: '刘希夷' },
  { text: '君不见高堂明镜悲白发，朝如青丝暮成雪。', author: '李白' },
  { text: '夫天地者，万物之逆旅也；光阴者，百代之过客也。', author: '李白' },
  { text: '长风破浪会有时，直挂云帆济沧海。', author: '李白' },
  { text: '天生我材必有用，千金散尽还复来。', author: '李白' },
  { text: '会当凌绝顶，一览众山小。', author: '杜甫' },
  { text: '读书不觉已春深，一寸光阴一寸金。', author: '王贞白' },
  { text: '沉舟侧畔千帆过，病树前头万木春。', author: '刘禹锡' },
  { text: '千淘万漉虽辛苦，吹尽狂沙始到金。', author: '刘禹锡' },
  { text: '花开堪折直须折，莫待无花空折枝。', author: '杜秋娘' },
  { text: '老当益壮，宁移白首之心？穷且益坚，不坠青云之志。', author: '王勃' },
  { text: '东隅已逝，桑榆非晚。', author: '王勃' },
  { text: '莫等闲、白了少年头，空悲切。', author: '岳飞' },
  { text: '少年易老学难成，一寸光阴不可轻。未觉池塘春草梦，阶前梧叶已秋声。', author: '朱熹' },
  { text: '人生如逆旅，我亦是行人。', author: '苏轼' },
  { text: '且将新火试新茶，诗酒趁年华。', author: '苏轼' },
  { text: '竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。', author: '苏轼' },
  { text: '谁道人生无再少？门前流水尚能西！休将白发唱黄鸡。', author: '苏轼' },
  { text: '寄蜉蝣于天地，渺沧海之一粟。哀吾生之须臾，羡长江之无穷。', author: '苏轼' },
  { text: '惟江上之清风，与山间之明月，耳得之而为声，目遇之而成色。', author: '苏轼' },
  { text: '人生到处知何似，应似飞鸿踏雪泥。', author: '苏轼' },
  { text: '欲买桂花同载酒，终不似，少年游。', author: '刘过' },
  { text: '流光容易把人抛，红了樱桃，绿了芭蕉。', author: '蒋捷' },
  { text: '纸上得来终觉浅，绝知此事要躬行。', author: '陆游' },
  { text: '山重水复疑无路，柳暗花明又一村。', author: '陆游' },
  { text: '明日复明日，明日何其多。我生待明日，万事成蹉跎。', author: '钱福' },
  { text: '不经一番寒彻骨，怎得梅花扑鼻香。', author: '黄檗禅师' },
  { text: '千磨万击还坚劲，任尔东西南北风。', author: '郑燮' },
  { text: '落红不是无情物，化作春泥更护花。', author: '龚自珍' },
  { text: '花有重开日，人无再少年。', author: '《增广贤文》' },
  { text: '时间就是性命。无端的空耗别人的时间，其实是无异于谋财害命的。', author: '鲁迅' },
  { text: '时间就像海绵里的水，只要愿挤，总还是有的。', author: '鲁迅' },
  { text: '日拱一卒，功不唐捐。', author: '胡适' },
  { text: '怕什么真理无穷，进一寸有一寸的欢喜。', author: '胡适' },
  { text: '你来人间一趟，你要看看太阳。', author: '海子' },
  { text: '活在这珍贵的人间，太阳强烈，水波温柔。', author: '海子' },
  { text: '从明天起，做一个幸福的人。喂马，劈柴，周游世界。', author: '海子' },
  { text: '要有最朴素的生活和最遥远的梦想，即使明天天寒地冻，路遥马亡。', author: '海子' },
  { text: '人是为明天活着的，因为记忆中有朝阳晓露。', author: '老舍' },
  { text: '生活是种律动，须有光有影，有左有右，有晴有雨。', author: '老舍' },
  { text: '把活着的每一天，都看作生命的最后一天。', author: '海伦·凯勒' },
  { text: '你热爱生命吗？那么别浪费时间，因为时间是组成生命的材料。', author: '富兰克林' },
  { text: '一个人知道自己为什么而活，就可以忍受任何一种生活。', author: '尼采' },
  { text: '每一个不曾起舞的日子，都是对生命的辜负。', author: '尼采' },
  { text: '不能听命于自己者，就要受命于他人。', author: '尼采' },
  { text: '谁终将声震人间，必长久深自缄默；谁终将点燃闪电，必长久如云漂泊。', author: '尼采' },
  { text: '未经省察的人生不值得过。', author: '苏格拉底' },
  { text: '世上只有一种英雄主义，就是在认清生活的真相之后，依然热爱生活。', author: '罗曼·罗兰' },
  { text: '当他回首往事的时候，不因虚度年华而悔恨，也不因碌碌无为而羞愧。', author: '奥斯特洛夫斯基' },
  { text: '记住你即将死去，是帮助我做出人生重大抉择的最好方法。', author: '史蒂夫·乔布斯' },
  { text: '你的时间有限，所以不要浪费时间去过别人的生活。', author: '史蒂夫·乔布斯' },
  { text: '求知若饥，虚心若愚。', author: '《全球概览》' },
  { text: '我们如何度过每一天，当然就是我们如何度过这一生。', author: '安妮·迪拉德' },
  { text: '把每一天都当作单独的一生来活。', author: '塞涅卡' },
  { text: '我们并非拥有的时间太少，而是浪费掉的太多。', author: '塞涅卡' },
  { text: '人们吝惜财物，却肆意挥霍唯一真正该吝啬的东西——时间。', author: '塞涅卡' },
  { text: '你随时可以离开生命。让这一点决定你做什么、说什么、想什么。', author: '马可·奥勒留' },
  { text: '不要表现得好像你还拥有一万年可活。', author: '马可·奥勒留' },
  { text: '人不应恐惧死亡，而应恐惧从未真正开始活过。', author: '马可·奥勒留' },
  { text: '别再浪费时间争论一个好人应该是什么样子。去做一个。', author: '马可·奥勒留' },
  { text: '你还要等多久，才肯要求自己做到最好？', author: '爱比克泰德' },
  { text: '对未来的真正慷慨，是把一切献给现在。', author: '加缪' },
  { text: '在隆冬，我终于知道，我身上有一个不可战胜的夏天。', author: '加缪' },
  { text: '应当想象西西弗是幸福的。', author: '加缪' },
  { text: '凡是过往，皆为序章。', author: '莎士比亚' },
  { text: '黑夜无论怎样悠长，白昼总会到来。', author: '莎士比亚' },
  { text: '我荒废了时间，时间便把我荒废了。', author: '莎士比亚' },
  { text: '如果你因错过太阳而流泪，那么你也将错过群星。', author: '泰戈尔' },
  { text: '生如夏花之绚烂，死如秋叶之静美。', author: '泰戈尔' },
  { text: '天空没有翅膀的痕迹，而我已经飞过。', author: '泰戈尔' },
  { text: '纵有疾风起，人生不言弃。', author: '保罗·瓦勒里' },
  { text: '万物皆有裂痕，那是光照进来的地方。', author: '莱昂纳德·科恩' },
  { text: '永远年轻，永远热泪盈眶。', author: '杰克·凯鲁亚克' },
  { text: '生活不是等待风暴过去，而是学会在雨中起舞。', author: '维维安·格林' },
  { text: '每一天，都是你余生的第一天。', author: '谚语' },
  { text: '种一棵树最好的时间是十年前，其次是现在。', author: '非洲谚语' },
  { text: '记住，人终有一死。', author: '拉丁谚语 Memento mori' },
  { text: '把握今天。', author: '贺拉斯 Carpe diem' },
  { text: '你能在其中获得乐趣的浪费，就不算浪费时间。', author: '罗素' },
  { text: '人是一根能思想的苇草。', author: '帕斯卡' },
  ],

  // 繁体：与简中共用内容，仅繁体化
  'zh-TW': [
    { text: '盛年不來，一日難再晨。及時當勉勵，歲月不待人。', author: '陶淵明' },
    { text: '悟已往之不諫，知來者之可追。', author: '陶淵明' },
    { text: '逝者如斯夫，不捨晝夜。', author: '《論語》' },
    { text: '少壯不努力，老大徒傷悲。', author: '漢樂府《長歌行》' },
    { text: '對酒當歌，人生幾何！譬如朝露，去日苦多。', author: '曹操' },
    { text: '年年歲歲花相似，歲歲年年人不同。', author: '劉希夷' },
    { text: '君不見高堂明鏡悲白髮，朝如青絲暮成雪。', author: '李白' },
    { text: '長風破浪會有時，直掛雲帆濟滄海。', author: '李白' },
    { text: '會當凌絕頂，一覽眾山小。', author: '杜甫' },
    { text: '讀書不覺已春深，一寸光陰一寸金。', author: '王貞白' },
    { text: '花開堪折直須折，莫待無花空折枝。', author: '杜秋娘' },
    { text: '莫等閒、白了少年頭，空悲切。', author: '岳飛' },
    { text: '少年易老學難成，一寸光陰不可輕。', author: '朱熹' },
    { text: '人生如逆旅，我亦是行人。', author: '蘇軾' },
    { text: '且將新火試新茶，詩酒趁年華。', author: '蘇軾' },
    { text: '明日復明日，明日何其多。我生待明日，萬事成蹉跎。', author: '錢福' },
    { text: '時間就是性命。無端的空耗別人的時間，其實是無異於謀財害命的。', author: '魯迅' },
    { text: '時間就像海綿裡的水，只要願擠，總還是有的。', author: '魯迅' },
    { text: '日拱一卒，功不唐捐。', author: '胡適' },
    { text: '你來人間一趟，你要看看太陽。', author: '海子' },
    { text: '把活著的每一天，都看作生命的最後一天。', author: '海倫·凱勒' },
    { text: '你熱愛生命嗎？那麼別浪費時間，因為時間是組成生命的材料。', author: '富蘭克林' },
    { text: '每一個不曾起舞的日子，都是對生命的辜負。', author: '尼采' },
    { text: '未經省察的人生不值得過。', author: '蘇格拉底' },
    { text: '世上只有一種英雄主義，就是在認清生活的真相之後，依然熱愛生活。', author: '羅曼·羅蘭' },
    { text: '記住你即將死去，是幫助我做出人生重大抉擇的最好方法。', author: '史蒂夫·賈伯斯' },
    { text: '你的時間有限，所以不要浪費時間去過別人的生活。', author: '史蒂夫·賈伯斯' },
    { text: '求知若飢，虛心若愚。', author: '《全球概覽》' },
    { text: '把每一天都當作單獨的一生來活。', author: '塞涅卡' },
    { text: '人不應恐懼死亡，而應恐懼從未真正開始活過。', author: '馬可·奧勒留' },
    { text: '對未來的真正慷慨，是把一切獻給現在。', author: '加繆' },
    { text: '凡是過往，皆為序章。', author: '莎士比亞' },
    { text: '如果你因錯過太陽而流淚，那麼你也將錯過群星。', author: '泰戈爾' },
    { text: '生如夏花之絢爛，死如秋葉之靜美。', author: '泰戈爾' },
    { text: '縱有疾風起，人生不言棄。', author: '保羅·瓦勒里' },
    { text: '萬物皆有裂痕，那是光照進來的地方。', author: '萊昂納德·科恩' },
    { text: '永遠年輕，永遠熱淚盈眶。', author: '傑克·凱魯亞克' },
    { text: '每一天，都是你餘生的第一天。', author: '諺語' },
    { text: '種一棵樹最好的時間是十年前，其次是現在。', author: '非洲諺語' },
    { text: '記住，人終有一死。', author: '拉丁諺語 Memento mori' },
    { text: '把握今天。', author: '賀拉斯 Carpe diem' },
  ],

  // 日本語：日本文化の名言、時間・命・今を生きる（『方丈記』『徒然草』芭蕉・漱石・賢治など）
  ja: [
    { text: '古きを温めて新しきを知る', author: '孔子『論語』' },
    { text: 'ゆく川の流れは絶えずして、しかももとの水にあらず', author: '鴨長明『方丈記』' },
    { text: 'つれづれなるままに、日暮らし、硯に向ひて', author: '吉田兼好『徒然草』' },
    { text: '世の中の事、何事もあらましに見ねば、さも心得たるやうに覚え', author: '吉田兼好『徒然草』' },
    { text: '五月雨を集めて早し最上川', author: '松尾芭蕉' },
    { text: '閑さや岩にしみ入る蝉の声', author: '松尾芭蕉' },
    { text: '夏草や兵どもが夢の跡', author: '松尾芭蕉' },
    { text: '旅人と我が名よばれん初しぐれ', author: '松尾芭蕉' },
    { text: '人間は本来善なるものなれば、悪をなすは心の狂へるなり', author: '夏目漱石『こころ』' },
    { text: '人生は一冊の本のごとく、その初めは希望、終わりは悔恨', author: '夏目漱石' },
    { text: '今日の事は今日のうちにせよ、明日は明日の風が吹く', author: '夏目漱石' },
    { text: '雨ニモマケズ風ニモマケズ雪ニモ夏ノ暑サニモマケヌ', author: '宮沢賢治' },
    { text: '世界がぜんたい幸福にならないうちは個人の幸福はあり得ない', author: '宮沢賢治『銀河鉄道の夜』' },
    { text: '誰も彼も他人の事に忙しくて自分の事はほったらかし', author: '太宰治『人間失格』' },
    { text: '生れた時から「自分」なんてないのだ', author: '太宰治『人間失格』' },
    { text: '美しく生きようと努める事それが人生の意味だ', author: '太宰治' },
    { text: '美しい人生は美しい心から', author: '川端康成' },
    { text: '人間は孤独であるべきだ', author: '川端康成' },
    { text: '地獄は人間の心の中にある', author: '芥川龍之介' },
    { text: '人生は地獄よりも悲惨であるただし人間は地獄よりも強い', author: '芥川龍之介' },
    { text: '我々は過去を生きている未来は我々のうちにある', author: '三島由紀夫' },
    { text: '一日を一日として確実に生きる', author: '三島由紀夫' },
    { text: '過去に執着する者は未来を失う', author: '三島由紀夫' },
    { text: '人生はただ一度きりの旅', author: '三浦綾子' },
    { text: '人間は生まれながらにして死を知っているだからこそ生きる意味を問う', author: '三浦綾子' },
    { text: '失敗は成功のもと', author: 'ことわざ' },
    { text: '継続は力なり', author: 'ことわざ' },
    { text: '石の上にも三年', author: 'ことわざ' },
    { text: '塵も積もれば山となる', author: 'ことわざ' },
    { text: '時は金なり', author: 'ことわざ' },
    { text: '今日を愛し今日を楽しむ', author: '宮本武蔵『五輪書』' },
    { text: '今を生きる過去に縛られず未来に怯えず', author: '松下幸之助' },
    { text: '一日一生今日を大事に生きる', author: '川瀬敏郎' },
    { text: '一日を一生と思いて過ごす', author: '道元『正法眼蔵』' },
    { text: '生きるということは死ぬことの準備である', author: '小林秀雄' },
  ],

  // English: 西方世界名言，主题：时间、生命、珍惜当下、memento mori、carpe diem
  // 英文原文，可查证；译文出处见各 author 标注
  en: [
    { text: 'Carpe diem, quam minimum credula postero.', author: 'Horace, Odes I.11' },
    { text: 'You could leave life right now. Let that determine what you do and say and think.', author: 'Marcus Aurelius, Meditations 2.11' },
    { text: 'Not to live as if you had endless years ahead of you. Death overshadows you. While you\u2019re alive and able\u2014be good.', author: 'Marcus Aurelius, Meditations 4.17' },
    { text: 'Death hangs over thee. While thou livest, while it is in thy power, be good.', author: 'Marcus Aurelius, Meditations 4.17' },
    { text: 'Remember that man lives only in the present, in this fleeting instant; all the rest of his life is either past and gone, or not yet revealed.', author: 'Marcus Aurelius, Meditations 3.10' },
    { text: 'I am endeavouring to live every day as if it were a complete life.', author: 'Seneca, Letters 101' },
    { text: 'As long as you live, keep learning how to live.', author: 'Seneca, Letters 76' },
    { text: 'What man can you show me who places any value on his time, who reckons the worth of each day, who understands that he is dying daily?', author: 'Seneca, Letters 1' },
    { text: 'It is indeed foolish to be unhappy now because you may be unhappy at some future time.', author: 'Seneca, Letters 13' },
    { text: 'He who should teach men to die would at the same time teach them to live.', author: 'Michel de Montaigne' },
    { text: 'The thing I fear most is fear.', author: 'Michel de Montaigne, Essays I.18' },
    { text: 'I want death to find me planting my cabbages.', author: 'Michel de Montaigne' },
    { text: 'Write it on your heart that every day is the best day in the year.', author: 'Ralph Waldo Emerson' },
    { text: 'The mass of men lead lives of quiet desperation.', author: 'Henry David Thoreau, Walden' },
    { text: 'I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.', author: 'Henry David Thoreau, Walden' },
    { text: 'I wanted to live deep and suck out all the marrow of life.', author: 'Henry David Thoreau, Walden' },
    { text: 'How we spend our days is, of course, how we spend our lives.', author: 'Annie Dillard, The Writing Life' },
    { text: 'Tomorrow, and tomorrow, and tomorrow, creeps in this petty pace from day to day, to the last syllable of recorded time; and all our yesterdays have lighted fools the way to dusty death.', author: 'William Shakespeare, Macbeth' },
    { text: 'Out, out, brief candle! Life\u2019s but a walking shadow, a poor player that struts and frets his hour upon the stage, and then is heard no more.', author: 'William Shakespeare, Macbeth' },
    { text: 'Real generosity toward the future consists in giving all to the present.', author: 'Albert Camus, Neither Victims nor Executioners' },
    { text: 'My field, said Goethe, is time.', author: 'Albert Camus, The Myth of Sisyphus' },
    { text: 'The eternal silence of these infinite spaces alarms me.', author: 'Blaise Pascal, Pens\u00e9es' },
    { text: 'Be not swept off your feet by the vividness of the impression, but say, "Impression, wait for me a little. Let me see what you are and what you represent."', author: 'Epictetus' },
    { text: 'Remembering that I\u2019ll be dead soon is the most important tool I\u2019ve ever encountered to help me make the big choices in life.', author: 'Steve Jobs, Stanford 2005' },
    { text: 'Your time is limited, so don\u2019t waste it living someone else\u2019s life.', author: 'Steve Jobs, Stanford 2005' },
    { text: 'Stay hungry. Stay foolish.', author: 'Steve Jobs, Stanford 2005' },
    { text: 'Death is very likely the single best invention of Life. It is Life\u2019s change agent. It clears out the old to make way for the new.', author: 'Steve Jobs, Stanford 2005' },
    { text: 'You\u2019ve got to find what you love. And that is as true for your work as it is for your lovers.', author: 'Steve Jobs, Stanford 2005' },
    { text: 'Do you want to spend the rest of your life selling sugared water, or do you want a chance to change the world?', author: 'Steve Jobs' },
    { text: 'This is what you shall do: Love the earth and sun and the animals, despise riches, give alms to every one that asks.', author: 'Walt Whitman' },
    { text: 'Memento mori.', author: 'Latin maxim' },
    { text: 'Tempus fugit.', author: 'Latin maxim' },
  ],

  // 한국어: 한국 문학·사상가의 명구를 중심으로, 시간·생명·지금·memento mori 주제
  // 공개된 시(시비·문집 등)에서 널리 인용되는 구절을 사용하였으며, 번역 명언은 한국어역을 따름
  ko: [
    { text: '지금은 싸움이 급하다. 나의 죽음을 알리지 말라.', author: '이순신' },
    { text: '죽고자 하면 살고, 살고자 하면 죽는다.', author: '이순신' },
    { text: '나의 이 거사는 동양 평화를 위하여 결행한 것이므로, 한·일 화합에 힘써 동양 평화에 이바지하기 바란다.', author: '안중근' },
    { text: '한양을 벗어나는 순간 기회는 사라지니, 무슨 일이 있어도 한양에서 버텨라.', author: '정약용' },
    { text: '님은 갔습니다. 아아, 사랑하는 나의 님은 갔습니다.', author: '한용운' },
    { text: '아아, 님은 갔지마는 나는 님을 보내지 아니하였습니다.', author: '한용운' },
    { text: '사랑도 사람의 일이라, 맛날 때에 미리 떠날 것을 염려하고 경계하지 아니한 것은 아니지만, 이렇게 하고 보니 그리워하는 마음이 더 크게 됩니다.', author: '한용운' },
    { text: '죽음의 굿판을 당장 걷어 치워라.', author: '김지하' },
    { text: '죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를, 잎새에 이는 바람에도 나는 괴로워했다.', author: '윤동주' },
    { text: '괴로웠던 사나이, 행복한 예수 그리스도에게, 처럼 십자가가 허락된다면.', author: '윤동주' },
    { text: '까마득한 날에 하늘이 처음 열리고, 어데 닭 우는 소리 들렸으랴.', author: '이육사' },
    { text: '지금 눈 내리고 매화 향기 홀로 아득하니, 내 여기 가난한 노래의 씨를 뿌려라.', author: '이육사' },
    { text: '다시 천고의 뒤에 백마 타고 오는 초인이 있어, 이 광야에서 목놓아 부르게 하리라.', author: '이육사' },
    { text: '이러매 눈 감아 생각해 볼밖에, 겨울은 강철로 된 무지갠가 보다.', author: '이육사' },
    { text: '나는 아직 기다리고 있을 것이며, 다음 모란이 피기까지는.', author: '이육사' },
    { text: '나 보기가 역겨워 가실 때에는, 말없이 고이 보내 드리오리다.', author: '김소월' },
    { text: '내가 그의 이름을 불러주기 전에는, 그는 다만 하나의 몸짓에 지나지 않았다.', author: '김춘수' },
    { text: '내가 그의 이름을 불러주었을 때, 그는 나에게 와 꽃이 되었다.', author: '김춘수' },
    { text: '우리가 섞인 자리에 꽃이 피고, 그 꽃의 이름은 우리라 부르리다.', author: '김춘수' },
    { text: '풀이 눕는다. 바람이 불어서 풀이 눕는다.', author: '김수영' },
    { text: '풀은 눕는다. 바람이 부는 일보다 더 빨리 일어나는 일.', author: '김수영' },
    { text: '태양을 의논하는 거룩한 이야기는 항상 태양을 등진 곳에서만 비롯하였다.', author: '신석정' },
    { text: '온 곳으로 되돌아가며, 온 곳으로 되돌아가자.', author: '류시화' },
    { text: '때가 가면 올사람이 오고, 갈 사람이 가는 것이어늘, 마음을 다해 사랑하고 미련 없이 보내세.', author: '김상옥' },
    { text: '오늘 할 일을 내일로 미루지 마라, 내일은 또 그만의 하늘이 있다.', author: '한국 속담' },
    { text: '시간은 금이라, 잃은 시간은 다시 오지 않는다.', author: '한국 속담' },
    { text: '우리는 매일 죽는다. 인간은 잘 죽는 법을 알지 못하는 한 잘 살 수 없다.', author: '세네카' },
    { text: '사는 동안 무엇을 가졌느냐로 따지지 말고, 무엇을 남겼느냐로 따져라.', author: '세네카' },
    { text: '진리는 모두에게 열려 있으며, 아직 누구도 그것을 독점한 적이 없다.', author: '세네카' },
    { text: '나뭇잎들을, 바람이 지표면에 있는 것들을 날려 버린다. 이것들은 인간의 자손들과 같다.', author: '마르쿠스 아우렐리우스' },
    { text: '존재하는 것들 가운데 어떤 것은 우리에게 달려 있는 것이고, 다른 어떤 것은 우리에게 달려 있지 않다.', author: '에픽테토스' },
    { text: '죽음을 기억하라. 살아 있는 동안, 살 수 있는 동안, 선한 사람이 되어라.', author: '마르쿠스 아우렐리우스' },
    { text: '죽음이 아니라, 아직 살아 보지 않은 것을 두려워해야 한다.', author: '마르쿠스 아우렐리우스' },
    { text: '사는 날을 헛되이 보내지 말아라, 젊음은 다시 오지 않는다.', author: '한국 속담' },
    { text: '지나간 시간을 붙잡으려 하지 말고, 다가올 시간에 마음을 다하여 살아라.', author: '한국 속담' },
  ],
};

/** 取某语言的名言池（缺池回退 zh-CN，保证任何语言都有内容） */
export function quotesForLang(lang) {
  return QUOTES[lang] || QUOTES['zh-CN'];
}

/** 按「一年中的第几天」取当天的名言 */
export function quoteOfDay(lang, dayOfYear) {
  const pool = quotesForLang(lang);
  return pool[((dayOfYear % pool.length) + pool.length) % pool.length];
}
